### ISSUE TITLE
Install on Ubuntu Server

### ISSUE THREAD

**Issue by 1moere1** [martinmicunda/ionic-photo-gallery#6]
What would I have to change/do to run the backend on my ubuntu 12 server? Do you have any solution or tutorial for this?

**Comment by martinmicunda** [comment]
You would need to change your base Vagrant box image specify [here](https://github.com/martinmicunda/ionic-photo-gallery/blob/master/Vagrantfile#L24) and I also believe you would need to change lib for android sdk specify [here](https://github.com/martinmicunda/ionic-photo-gallery/blob/master/ansible%2Fplaybook.yml#L19)
